SDK_DIR=/Developer/SDKs/MacOSX10.4u.sdk

all:	Makefile

Makefile:	Makefile.xcode configure Makefile.in
	CFLAGS="-O0 -g -D_POSIX_C_SOURCE=200112L -arch i386 -arch ppc -isysroot $(SDK_DIR)" LDFLAGS="-Wl,-syslibroot,$(SDK_DIR) -arch i386 -arch ppc -fno-common" ./configure --prefix=$(BUILT_PRODUCTS_DIR) --disable-dependency-tracking --with-libiconv-prefix=$(SDK_DIR)/usr

clean:
	test -f Makefile && make distclean