SDK_DIR=/Developer/SDKs/MacOSX10.4u.sdk

all:	Makefile

Makefile:	Makefile.xcode configure Makefile.in config.h.in
	CFLAGS="-O -g -arch i386 -arch ppc -isysroot $(SDK_DIR)" LDFLAGS="-arch i386 -arch ppc" ./configure --prefix=/usr/local --disable-dependency-tracking

clean:
	test -f Makefile && make distclean