SDK_DIR=/Developer/SDKs/MacOSX10.4u.sdk

all:	Makefile

Makefile:	Makefile.xcode configure Makefile.in config.h.in
	CC=gcc-4.0 CFLAGS="-O -g -arch i386 -arch ppc -isysroot $(SDK_DIR)" LDFLAGS="-arch i386 -arch ppc" ./configure --prefix=/usr/local --disable-dependency-tracking

clean:
	echo "warning: pkg-config not cleaned. if you really want to clean MILib, do a git reset/git clean of your MILibs."
